# -*- coding: utf-8 -*-
"""DAS-511

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vGRBeNp4GLaxyw3KgOp9kSaTYCICGg8P
"""

import random 

a = input('Please enter your name: ')
f = input('Plese enter your favorite fruit: ')
b = f+"s"
c = input('Now enter your favorite number: ')

n = random.randint(0,1000) 
sum = float(c)+float(n)



print("'Welcome to my basic python code",a)
print("Based on your inputs, this program has generated a random number between 0 and 1000")
print("That number was then added to", n)
print("A magic wizard will bring you", sum, b)

