# -*- coding: utf-8 -*-
"""Cheat-sheet_for_Google_Colab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/Tanu-N-Prabhu/Python/blob/master/Cheat_sheet_for_Google_Colab.ipynb

# **Cheat-sheet for Google Colab**

## **In this tutorial, you will learn how to make the most out of Google Colab.**

![alt text](https://miro.medium.com/max/1400/1*7oukapIBInsovpHkQB3QZg.jpeg)

# **Introduction**

[Google Colab](https://colab.research.google.com/notebooks/intro.ipynb) is an amazing tool that lets us build and execute an outstanding data science model and provides us with an opportunity to document our journey. As Google Colab provides us **code cells** to type the code, it also provides us with text cells to add the text. In this tutorial, we will focus more on the **text cell** and see how we can master it by using some simple commands that I will discuss in this tutorial. If you love documenting (like me) then you will enjoy reading this tutorial. You can start exploring Google Colab from below given link. Believe me, it’s an amazing tool.

**Get your hands on [Google Colab](https://colab.research.google.com/)**



---

# **Cheat-sheet**


Below I will discuss some main handy tricks and shortcuts that can use and become a pro in documenting. If you know [Markdown](https://www.markdownguide.org/), [XML](https://www.w3schools.com/xml/), and [HTML](https://www.w3schools.com/html/) coding then this might be a cakewalk or if you are not familiar with either of those well today is the day to learn them all. Google Colab supports both **Markdown** and **HTML** documentation. You can any of these to document. All right, let’s get started.




> **To experiment with all of these commands use the “Text cell”**


![alt text](https://miro.medium.com/max/1400/1*6N4h9SMdf-NLWEIWAzeEJQ.png)



---

# **Heading**

Below is the shortcut command for headings. There are different types of headings from Heading 1 to 6.


## **Markdown**

Use `# heading-name`, the more you append `#` the size of the heading decreases as seen below:


![alt text](https://miro.medium.com/max/1400/1*FvhQEnugHOYcOu9hTTiloQ.png)


## **HTML**

Similarly, you can use HTML tags such as h1, h2, h3, h4, h5 and h6 for headings as shown below:

![alt text](https://miro.medium.com/max/1400/1*YeuY2GRIDZc1hZGBG8UGEQ.png)



---

# **Bold**

Bold make the text bolder and increases the text’s visibility.

## **Markdown**

To make the text bold in markdown surround it by `**` (two stars) for example `**Text-to-be-bold**`.

![alt text](https://miro.medium.com/max/1400/1*F10Z_262d18oRCRuIPUJtw.png)

## **HTML**

Using HTML we can bold the text by using the b tag as seen below:


![alt text](https://miro.medium.com/max/1400/1*gd_RowfxD646hGn4jkqwCQ.png)



---

# **Italicize**

Similar to bold the text can also be italicized

## **Markdown**

To make the text italicize in markdown surround it by `*` (one star) for example `*Text-to-be-italicize*`

![alt text](https://miro.medium.com/max/1400/1*qnD2cKIhia7pxGUwXDtHGQ.png)


## **HTML**

Also, this can be written in HTML using the i tag as shown below:

![alt text](https://miro.medium.com/max/1400/1*P0g65RLoMraJ8820WzToPw.png)



---

# **Strikethrough**

Used to strike through the text. A **horizontal line** is drawn in the middle of the text.

## **Markdown**

To strikethrough, the text in markdown surround the text with two tilde’s character `~~`, such as `~~Text to be striked~~`.

![alt text](https://miro.medium.com/max/1400/1*5vU7QHc4XS0YMA9jHUbFLg.png)

## **HTML**

In HTML we can use the s tag to strikethrough the text.

![alt text](https://miro.medium.com/max/1400/1*ONCvW5n_qqrnhFBXwb4mFg.png)



---

# **Combination**

Also, we can combine all the formatting commands and style the text as shown below.

## **Markdown and HTML**

![alt text](https://miro.medium.com/max/1400/1*h1y2_-st5Rugd2sDXSkUJQ.png)



---

# **Lists**

As we all know there are two types of lists:



1.   **Ordered List**

2.   **Unordered List**

As the name suggests an ordered list has an order (1, 2, 3,… or other). But an unordered list has no order, as shown below.

## **Ordered and Unordered list in Markdown**

In markdown for the ordered list, you can straightaway just type numbers like `1, 2, 3, and so on`. But for the unordered list, you can start with a `*` and this intern creates a bullet list.

![alt text](https://miro.medium.com/max/1400/1*vBRF_lB35gRkuH09Msx9bA.png)

## **HTML**

We can use the HTML tags to play with the lists as shown below:

## **Ordered list**

In the ordered list there are **normal list, type 1, A, a, I, i types** as shown below:

**Normal list**

Use the `ol` tag and for the list contents use the `li` tag as shown below:

![alt text](https://miro.medium.com/max/1400/1*kcDBziqmKvYyl3Hv_LBUiw.png)

**Type = “1”**

Just add `type = "1"` inside the ol tag this will create an ordered list of **1, 2, 3, and so on**. The list items will be numbered with numbers (default).

![alt text](https://miro.medium.com/max/1400/1*09W5HYQIUJ4LcfJPWw1vsQ.png)

**Type = “A”**

Just add `type = "A"` inside the ol tag this will create an ordered list of **A, B, C, and so on**. The list items will be numbered with uppercase letters.

![alt text](https://miro.medium.com/max/1400/1*67oeYyf0gfliUoqI0ABDpg.png)

**Type = “a”**
Just add `type = "a"` inside the ol tag this will create an ordered list of **a, b, c, and so on**. The list items will be numbered with lowercase letters.

![alt text](https://miro.medium.com/max/1400/1*vtCQpk6uO2DpU3KKmfqtLg.png)


**Type = “I”**

Just add `type = "I"` inside the ol tag this will create an ordered list of **I, II, III, and so on**. The list items will be numbered with uppercase roman numbers.

![alt text](https://miro.medium.com/max/1400/1*rt09GDABSFkU502NmSH9_g.png)

**Type = “i”**

Just add `type = "i"` inside the ol tag this will create an ordered list of **i, ii, iii, and so on**. The list items will be numbered with lowercase roman numbers.

![alt text](https://miro.medium.com/max/1400/1*dN-5gR4xgtf9jwWF_ZOYtw.png)




---

## **Unordered list**

In the ordered list there are **normal list, disc, square, circle, and none types** as shown below:

**Normal list**

Use the `ul` tag and for the list contents use the `li` tag as shown below:

![alt text](https://miro.medium.com/max/1400/1*Q6gRYUpdx1RX5DTrPsuQPQ.png)



---

**Disc**

Just add `type = "disc"` inside the `ul` tag to create a disc-shaped list.

![alt text](https://miro.medium.com/max/1400/1*_O-1sIf7JZadHKG71gOvWw.png)

---

**Circle**

Just add `type = "circle"` inside the `ul` tag to create a circle-shaped list.

![alt text](https://miro.medium.com/max/1400/1*sfDKOF21OqcLoEYLiZ8lcw.png)

---

**Square**

Just add `type = "square"` inside the `ul` tag to create a square-shaped list.

![alt text](https://miro.medium.com/max/1400/1*4G-LWW2LWiZM1VpJPqSgDA.png)

---

**None**

Just add `type = "none"` inside the `ul` tag to create a none-shaped list. In this case, the list will have no points as shown below:

![alt text](https://miro.medium.com/max/1400/1*jXzBSc7gnBClrvDqmJpSWA.png)

---

## **Description list**


A description list is a list of terms, with a description of each term. The `dl` tag consists `dt` which defines the name of the list and the `dd` tag describes each list.

![alt text](https://miro.medium.com/max/1400/1*D8XzV7hC0Zro_Zzm8o0Fpg.png)


---

## **Nested list**

Nested lists are basically lists within lists.

![alt text](https://miro.medium.com/max/1400/1*S4WnDBD2Xty4DDVRw-ggYQ.png)

---

## **Control list counting**

An ordered list will start counting from 1. If you want to count from a specified number, you can use the `start` attribute as shown below:

![alt text](https://miro.medium.com/max/1400/1*1Ab0qTWvQY08l9NWA1S8Rw.png)

To know more in-depth about the list in HTML please refer to the article below:

[HTML Lists](https://www.w3schools.com/html/html_lists.asp)

---

# **Links**

Links or hyperlinks allow users to click their way from page to page.

## **Markdown**

In markdown write the title of the link inside square brackets `[ ]` and write the webpage address inside round brackets or parenthesis `( )`. **Make sure you write the title first, followed by the link.**

![alt text](https://miro.medium.com/max/1400/1*QJf4inbel4zdf9i8hndr3g.png)

## **HTML**

In HTML for the hyperlinks, you can use the anchor `a` and `href` tag as shown below:

![alt text](https://miro.medium.com/max/1400/1*X0kAxZW6CfbXl81PHdyu6Q.png)

---

# **Images**

Sometimes **one image is worth one thousand words**. People can easily understand the concepts better by seeing an image.

## **Markdown**

Similar to the link you need to insert the link of the image inside the parenthesis. Make sure you append `!` at the beginning. If your link is broken or not valid, then the `alt text` would be displayed.

![alt text](https://miro.medium.com/max/1400/1*Bk6dec-nG1PuAJv3PjZq9w.png)

**Image hover**

You can simultaneously hover on the text to see the title of the image. To do this, you can put the text of your choice inside the command as shown below:



```
![alt text](https://media.makeameme.org/created/online-class-cant.jpg "Online Class Memes")

```
## **HTML**

In HTML we can include an image using the img tag and you need to provide the source of the image to the src tag.

**Adjusting height and width**

You can adjust the **height** and **width** of the image. Also, you can embed a **GIF** image too as shown below.

![alt text](https://miro.medium.com/max/1400/1*iFiRv_AlSwL5RQ8tkTf_6w.png)

**Images along with captions**

It’s a great practice to give credit to the images taken from different sources (I mean citing the images or providing the captions). With the help of `figcaption` tag we can provide captions to the images.

![alt text](https://miro.medium.com/max/1400/1*9IWjFlKTBogYWuH3G1zKhw.png)

You can play with the `align` tag and try to align the caption according to your preference.

---

# **Format the code**

There are two things that you need to understand here are:


1.   **Inline Code**
2.   **Syntax highlighting**


## **Inline Code**

Sometimes you might want to insert a few code samples you can use Inline codes. To use the inline code, you can use the **backticks (``)**. Surround it with backticks as shown above.


![alt text](https://miro.medium.com/max/1400/1*jTJnPDH_LY7SHoA8NCSFgw.png)

---

## **Syntax highlighting**

This is used when you write **huge lines of codes** inside Google Colab’s text editor. Sometimes including huge python code snippets is not a good idea using inline codes, use syntax highlight in this case. You must embed the code within ` ``` ` as shown below:


**Default syntax highlighting**

This works irrespective of any programming language.

![alt text](https://miro.medium.com/max/1400/1*uBqi2TGiII8XGUWFNFN3Wg.png)


**Python syntax highlighting**

This can be used explicitly for **python** programming. You should include the name `python` at the beginning.

![alt text](https://miro.medium.com/max/1400/1*8ikLv5cwvPAawt97Q1xrTg.png)


**Javascript syntax highlighting**

This can be used explicitly for **JavaScript** programming. You should include the name `javascript` at the beginning.

![alt text](https://miro.medium.com/max/1400/1*mjXD9EB0ZQCYFBBZdgs4KQ.png)

**C programming syntax highlighting**

This can be used explicitly for **C** programming. You should include the name `c` at the beginning.

![alt text](https://miro.medium.com/max/1400/1*28aomzI0HhUJHxphJfpfZw.png)


As seen above you can highlight the code snippets based on different programming languages.

---

# **Tables**

There are a few times you might want to represent the information in the form of **tables**.

## **Markdown**
You must use the `|` as an operator for different columns. By default, the table headers would be in bold.

![alt text](https://miro.medium.com/max/1400/1*7FdxLfShsePvU_FQ-qqS3Q.png)



> Colons can be used to align columns.


If you need to create any table then use the below [tool](https://www.tablesgenerator.com/) to generate tables for you. All you have to do select the type of table generators such as **Latex, HTML, Markdown, and others**. Enter the contents inside the table and then click on **Generate**. You can then copy-paste the generated code in the text editor and see a beautiful table without minimum effort.

[Create LaTeX tables online](https://www.tablesgenerator.com/)

## **HTML**

In the case of HTML, you must use the `table` tag along with `tr` which is for the table rows and `th` is for the table headers (**Company Name and Founder**) in this case. The `td` is for the table description.

![alt text](https://miro.medium.com/max/1400/1*ShqEpogTHh9pA95sWjA2DQ.png)


You can also use the `align` tag and align the contents accordingly.

---

# **Indent**

This is very useful when you need to differentiate some text like **NOTE, HINT** or any extra useful information.

## **Markdown**

You need to use the `>` for the indentation.

![alt text](https://miro.medium.com/max/1400/1*e3s2rKSTdp0RmxlmbdkmYw.png)


## **HTML**

Similarly in HTML you can use the `blockquote` tag for the same purpose.

![alt text](https://miro.medium.com/max/1400/1*zS3GwuK3SmFQq_6Jt-GsUA.png)


---

# **Horizontal Ruler**


It is often a wonderful practice to draw a horizontal ruler after every chapter, or any concept while you are writing. This just helps in differentiating things from one another.

## **Markdown**

In case of markdown, you need to just use 3 `---` (Minus).

![alt text](https://miro.medium.com/max/1400/1*VSkk-UQvxbGom2bVCIvAwQ.png)

## **HTML**

In case of HTML, you need to use the tag `hr` for inserting a horizontal ruler.

![alt text](https://miro.medium.com/max/1400/1*H5kmuc_KSaRB90FOCZfMpQ.png)


---

# **Justify**

Often many times you will write big paragraphs in your notebooks, but sometimes you might want to justify them just to make it look neat. Here, you can use the `align` tag with `justify` as a value.

![alt text](https://miro.medium.com/max/1400/1*liOB0s27ECQUhWd-HGKgsw.png)


![alt text](https://miro.medium.com/max/1400/1*P_hLZhBhf4OZYRdJ3nJyYg.png)



Similarly, you can use `right`, `left`, and `center` values and **align** the paragraph accordingly.

---

# **Line break**

Some times you might want to start a new paragraph, so you will need to put a line break in between both of them. There are two options here either you can just press the **“Enter”** key and leave a line of space in the between or you can use the `br` tag also called a line break.

![alt text](https://miro.medium.com/max/1400/1*yJ3VKVl-q7yeYn_Uw_5EXg.png)

---

# **Mathematical formulas**

If you are using the notebooks for research purpose then you need to write a lot of equations and mathematical symbols.

## **Symbols**

Make sure you write the symbol name between `$` and start with `\` after the first `$`.

![alt text](https://miro.medium.com/max/1400/1*578h3YR_ItAA1O9lQNkcjQ.png)


## **Equations**

Follow the same rules i.e surround the equations between `$` and start with `/` after the first `$`.

![alt text](https://miro.medium.com/max/1400/1*5tRMzSc_wLHIXB3rNrKi5Q.png)

To see more about the mathematical equations and symbols, please refer to the [link](https://csrgxtu.github.io/2015/03/20/Writing-Mathematic-Fomulars-in-Markdown/) below:

[Writing Mathematical Formulas in Markdown](https://csrgxtu.github.io/2015/03/20/Writing-Mathematic-Fomulars-in-Markdown/)

---

All right, folks, that’s the end of the tutorial. I hope you learned many new things today. I tried to keep this tutorial short but as there were many concepts I had to maximize it. But this cheat-sheet will be useful in most of the interviews (**technical documentation**) or when you are documenting your Jupiter notebooks. If I find more tips and tricks, then I will provide the details here. Until then, stay safe and have a wonderful day. See you next time.
"""